/*
     [조인] 주문량이 많은 아이스크림들 조회하기 (타인의 풀이)
*/
SELECT F.FLAVOR
FROM FIRST_HALF F
RIGHT JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
            FROM JULY
            GROUP BY FLAVOR) J
ON F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER+J.TOTAL_ORDER DESC
LIMIT 3;